apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  # parallelism: 3
  completions: 3
  template:
    spec:
      containers:
      - name: busybox-marek
        image: busybox
        command: ['echo', 'Hello from the job']
      restartPolicy: Never
