apiVersion: v1
kind: Pod
metadata:
  name: "mybox"
  labels:
    app: cos
spec:
  containers:
  - name: mybox
    image: busybox
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    command:
    - sleep
    - "3600"
  restartPolicy: Always