apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: marekrs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: marek
      type: front-end
  template:
    metadata:
      name: myapp-pod
      labels:
        app: marek
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 500Mi      
        ports:
        - containerPort:  80
    