apiVersion: v1
kind: Pod
metadata:
  name: init-mydb
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 500Mi      
    ports:
    - containerPort:  80
    volumeMounts:
    - name: workdir
      mountPath: usr/share/nginx/html
  initContainers:
  - name: install
    image: alpine
    command:
    - wget
    - "-O"
    - "/work-dir/index.html"
    - http://info.cern.ch
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
  volumes:
    - name: workdir
      emptyDir: {}
